// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telhai.CS.APIServer.Models;

#nullable disable

namespace Telhai.CS.APIServer.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20230301094647_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telhai.CS.APIServer.Models.Exam", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("duration")
                        .HasColumnType("real");

                    b.Property<string>("examName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRandom")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Telhai.CS.APIServer.Models.Question", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Examid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("correct")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Examid");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Telhai.CS.APIServer.Models.Question", b =>
                {
                    b.HasOne("Telhai.CS.APIServer.Models.Exam", null)
                        .WithMany("questions")
                        .HasForeignKey("Examid");
                });

            modelBuilder.Entity("Telhai.CS.APIServer.Models.Exam", b =>
                {
                    b.Navigation("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
